### PR TITLE
1418 [Bug]: g_lineplot doesn't work with a format as a function

### LINKED ISSUE #1418: [Bug]: g_lineplot doesn't work with a format as a function
### What happened?

The bug is in `tern::h_format_row()`:

```R
library(tern)

x <- list(mean = 0.5, mean_ci = c(0.15, 1.15))

format <- list(
  mean = function (x, ...) {
    ifelse(x < 1, round_fmt(x, digits = 2), round_fmt(x, digits = 1))
  },
  mean_ci = "(xx.xx, xx.xx)"
)

formatted_row <- h_format_row(x, format)
print(formatted_row)
```

```
Error in if (is.na(fc)) { : argument is of length zero
```
<br/>

Image

### sessionInfo()

```R

```

### Relevant log output

```R

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [x] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [x] I agree to follow this project's Security Policy.

### PR DESCRIPTION
**Pull request by yurovska**
Fixes #1418

### CODE REVIEW

**Comment by yurovska** [comment]
@Melkiades I've also fixed `table_format` and `table_labels` args, which were completely ignored in the `g_lineplot`.

Ready for review.

File: R/g_lineplot.R [hunk 1]
```diff
@@ -185,8 +185,8 @@ g_lineplot <- function(df,
   checkmate::assert_logical(as_list)
 
   if (!is.null(table)) {
-    table_format <- get_formats_from_stats(table)
-    table_labels <- get_labels_from_stats(table) %>% .unlist_keep_nulls()
+    table_format <- get_formats_from_stats(table) %>% modifyList(table_format %||% list())
+    table_labels <- get_labels_from_stats(table) %>% modifyList(table_labels %||% list()) %>% .unlist_keep_nulls()
```
Comment (Melkiades) [inline R/g_lineplot.R:189]: Could you use the std format input? `tern::get_formats_from_stats(formats_in = )` you can also not force it in a list

Comment (yurovska) [reply R/g_lineplot.R:189]: Good point, thanks.

Comment (yurovska) [reply R/g_lineplot.R]: Done

**Comment by yurovska** [comment]
> It looks very good!! Can I ask you to add into the function reference about the possible `function` input? Thanks! :)

Thanks for your comment. Documentation has been slightly updated.

**Review by Melkiades — APPROVED** [review]
Looks great! Good to go. Thanks for the terrific job :)

**Comment by yurovska** [comment]
> Looks great! Good to go. Thanks for the terrific job :)

@Melkiades Thanks for the review. I do not have permission to merge, so please do so.
