### PR TITLE
Fix analysis function refactor bugs

### LINKED ISSUE #1405: Bug fixes for analysis function refactor
Fix integration tests.

TODO:

- [x] Fix `summarize_*()` function indentation
- [x] Update `count_occurrences()` default for empty data frames
- [x] Add processing for unnamed labels/formats

### PR DESCRIPTION
**Pull request by edelarua**
# Pull Request

Fixes #1405 

see checks downstream

- https://github.com/insightsengineering/chevron/pull/829 this is ok now
- https://github.com/insightsengineering/scda.test/pull/189/files this seems to have numbers changed.

### CODE REVIEW

File: R/utils_default_stats_formats_labels.R [hunk 1]
```diff
@@ -318,6 +327,15 @@ get_labels_from_stats <- function(stats,
   }
   checkmate::assert_list(levels_per_stats, null.ok = TRUE)
 
+  # If unnamed labels given as labels_in and same number of stats, use one label per stat
+  if (
+    !is.null(labels_in) && length(labels_in) == length(stats) &&
+      is.null(names(labels_in)) && is.null(levels_per_stats)
+  ) {
+    out <- as.list(labels_in) %>% setNames(stats)
+    return(out)
```
Comment (Melkiades) [inline R/utils_default_stats_formats_labels.R:336]: Could you add a test showcasing when this happens?

**Review by Melkiades — COMMENTED** [review]
Thanks Emily! Could you add only a regression test for the scda.test error

File: R/utils_default_stats_formats_labels.R (hunk 1 above)
Comment (edelarua) [reply R/utils_default_stats_formats_labels.R:336]: Test added!

Also, an example where this occurs in TLG-C is the "- Any Intensity -" rows in [AET03](https://insightsengineering.github.io/tlg-catalog/stable/tables/adverse-events/aet03.html).

**Comment by edelarua** [comment]
> hi @edelarua , can you please raise PRs downstream in scda.test and chevron and test this. Thank you!

scda.test: https://github.com/insightsengineering/scda.test/pull/189
chevron: https://github.com/insightsengineering/chevron/pull/829

**Review by Melkiades — APPROVED** [review]
For me it is good to merge when test PRs are ready. Thanks @edelarua!!

**Comment by edelarua** [comment]
@shajoezhu are we good to merge this one in?
