### PR TITLE
Fix snapshot differences (it may need muting `h_ppmeans()`)

### LINKED ISSUE #1058: Investigate variable printout for`summarize_glm_count`
```
✖ | 3      25 | summarize_glm_count [1.4s]                                      
  ────────────────────────────────────────────────────────────────────────────────
  Failure ('test-summarize_glm_count.R:185:3'): h_ppmeans works with healthy input
  Snapshot of code has changed:
  old vs new
    Code
      res
    Output
  -                  rate asymp.LCL asymp.UCL            ARM
  +                      rate asymp.LCL asymp.UCL            ARM
  -   A: Drug X      3.07  2.202774  4.278651      A: Drug X
  +   A: Drug X      9.029759  6.295928  12.95068      A: Drug X
  -   B: Placebo     3.07  2.202774  4.278651     B: Placebo
  +   B: Placebo     9.029759  6.295928  12.95068     B: Placebo
  -   C: Combination 3.07  2.202774  4.278651 C: Combination
  +   C: Combination 9.029759  6.295928  12.95068 C: Combination
  
  * Run `testthat::snapshot_accept('summarize_glm_count')` to accept the change.
  * Run `testthat::snapshot_review('summarize_glm_count')` to interactively review the change.
  
  Failure ('test-summarize_glm_count.R:206:3'): s_glm_count works with healthy input
  Snapshot of code has changed:
       old                     | new                           
   [5]   [1] 73                |   [1] 73                  [5] 
   [6]                         |                           [6] 
   [7]   $rate                 |   $rate                   [7] 
   [8]   [1] 3.486005          -   [1] 10.20612            [8] 
   [9]   attr(,"label")        |   attr(,"label")          [9] 
  [10]   [1] "Adjusted Rate"   |   [1] "Adjusted Rate"     [10]
  [11]                         |                           [11]
  [12]   $rate_ci              |   $rate_ci                [12]
  [13]   [1] 1.983340 6.127155 -   [1]  5.627535 18.509855 [13]
  [14]   attr(,"label")        |   attr(,"label")          [14]
  [15]   [1] "95% CI"          |   [1] "95% CI"            [15]
  [16]                         |                           [16]
  
  * Run `testthat::snapshot_accept('summarize_glm_count')` to accept the change.
  * Run `testthat::snapshot_review('summarize_glm_count')` to interactively review the change.
  
  Failure ('test-summarize_glm_count.R:229:3'): s_glm_count works with no reference group selected.
  Snapshot of code has changed:
       old                     | new                           
   [5]   [1] 73                |   [1] 73                  [5] 
   [6]                         |                           [6] 
   [7]   $rate                 |   $rate                   [7] 
   [8]   [1] 3.486005          -   [1] 10.20612            [8] 
   [9]   attr(,"label")        |   attr(,"label")          [9] 
  [10]   [1] "Adjusted Rate"   |   [1] "Adjusted Rate"     [10]
  [11]                         |                           [11]
  [12]   $rate_ci              |   $rate_ci                [12]
  [13]   [1] 1.983340 6.127155 -   [1]  5.627535 18.509855 [13]
  [14]   attr(,"label")        |   attr(,"label")          [14]
  [15]   [1] "95% CI"          |   [1] "95% CI"            [15]
  [16]                         |                           [16]
  
  * Run `testthat::snapshot_accept('summarize_glm_count')` to accept the change.
  * Run `testthat::snapshot_review('summarize_glm_count')` to interactively review the change.
```

### PR DESCRIPTION
**Pull request by Melkiades**
Fixes #1058 

The error comes ONLY from integration tests (mismatch of output rates and rate CI in `h_ppmeans()`). @ayogasekaram tested on docker image, @edelarua and I tested it (I think window-based rstudio and Ubuntu rstudio-server) and there are no differences in our snapshots, i.e. it is passing for all of us. Now I think this needs to come from `stats::predict` step in `h_ppmeans` as also rates are different. It seems we tested everything (adding random seed does not change my local snapshots). Could it have something to do with the system libraries? what do you think @cicdguy? If we cannot fix it, and it is not a fundamental feature we might want to turn it off. Is this function used in the biomarker catalog  @danielinteractive? To my knowledge, it is not used in the TLG-c, right @ayogasekaram @edelarua? 

Please refer to #1059 and integration tests for the changes that exclude the fit itself from having any changes local vs integration tests.

### CODE REVIEW

**Comment by danielinteractive** [comment]
This is not used in BAC AFAIK 👍🏼

**Comment by edelarua** [comment]
In TLG-C, `summarize_glm_count` is used only in RATET01. 

See context:

```r
  ...
  ) %>%
  summarize_glm_count(
    vars = "AVAL",
    variables = list(arm = "ARM", offset = "lgTMATRSK", covariates = NULL),
    conf_level = 0.95,
    distribution = "poisson",
    rate_mean_method = "emmeans",
    var_labels = "Unadjusted exacerbation rate (per year)",
    table_names = "unadj",
    .stats = c("rate"),
    .labels = c(rate = "Rate")
  ) %>%
  summarize_glm_count(
    vars = "AVAL",
    variables = list(arm = "ARM", offset = "lgTMATRSK", covariates = c("REGION1")),
    conf_level = 0.95,
    distribution = "quasipoisson",
    rate_mean_method = "ppmeans",
    var_labels = "Adjusted (QP) exacerbation rate (per year)",
    table_names = "adj",
    .stats = c("rate", "rate_ci", "rate_ratio", "rate_ratio_ci", "pval"),
    .labels = c(
      rate = "Rate", rate_ci = "Rate CI", rate_ratio = "Rate Ratio",
      rate_ratio_ci = "Rate Ratio CI", pval = "p value"
    )
  )
```

**Review by BFalquet — APPROVED** [review]

File: tests/testthat/test-summarize_glm_count.R [hunk 1]
```diff
@@ -186,6 +187,7 @@ testthat::test_that("h_ppmeans works with healthy input", {
 
   testthat::expect_snapshot(fits2)
 
+  # XXX ppmeans fails snapshot diff in integration tests
   result <- h_ppmeans(
```
Comment (Melkiades) [inline tests/testthat/test-summarize_glm_count.R:191]: Keeping this failing to see if set.seed helps and if also AVR is triggered by this change
