### PR TITLE
Fix `get_labels_from_stats` test

### LINKED ISSUE #1271: [bug] failing test
```
 ── Failed tests ────────────────────────────────────────────────────────────────
  Failure ('test-utils_default_stats_formats_labels.R:110:3'): get_labels_from_stats works as expected
  get_labels_from_stats(c("nothing", "n"))[["nothing"]] (`actual`) not identical to "" (`expected`).
  
  `actual`:   "nothing"
  `expected`: ""      

```

### PR DESCRIPTION
**Pull request by edelarua**
# Pull Request

Fixes #1271 

Also updates outdated graph snaps

### CODE REVIEW

**Review by ayogasekaram — APPROVED** [review]
lgtm! Thanks @edelarua

File: R/utils_default_stats_formats_labels.R [hunk 1]
```diff
@@ -514,7 +514,7 @@ tern_default_labels <- c(
 #' @export
 summary_formats <- function(type = "numeric", include_pval = FALSE) {
   lifecycle::deprecate_warn(
-    "0.9.0.9.5.9005", "summary_formats()",
+    "0.9.5.9005", "summary_formats()",
```
Comment (shajoezhu) [inline R/utils_default_stats_formats_labels.R:517]: lol. what happened here

Comment (edelarua) [reply R/utils_default_stats_formats_labels.R:517]: I'm not quite sure how that happened, but it looked like a typo so it's been fixed!!
